[tool.poetry]
name = "orwynn"
version = "0.3.7"
description = "Scalable web-framework with out-of-the-box architecture"
authors = ["ryzhovalex <thed4rkof@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.88.0"
uvicorn = {extras = ["standard"], version = "0.20.0"}
loguru = "0.6.0"
pyyaml = "6.0"
pytest = "7.2.0"
pyjwt = "2.6.0"
httpx = "0.23.1"
colorama = "0.4.6"
coverage = "6.5.0"
pymongo = "4.3.3"
python-dotenv = "0.21.0"
bcrypt = "4.0.1"
websockets = "10.4"
dictdiffer = "0.9.0"
python-benedict = "0.28.1"
pytest-asyncio = "0.20.3"
sqlalchemy = "2.0.3"
psycopg2 = "2.9.5"

[tool.poetry.group.dev.dependencies]
lorem = "0.1.1"
ruff = "0.0.215"
git-changelog = "1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
