select = ["ALL"]

fix = true
line-length = 79
respect-gitignore = true

exclude = [
    "docs/source/conf.py",
    ".vscode",
    "orwynn/legacy"
]

ignore = [
    "RUF012",
    "FIX002",
    # we love lambdas
    "E731",

    # gives false-positive
    "PD011",

    "BLE001",

    "FA102",

    # remove ugly trailing commas
    "COM812",

    # advent of asserts
    "S101",

    # we love long messages
    "TRY003",

    # allow free format of TODOs
    "TD",

    # preffered todo style includes keyword and author's name in parentheses.
    # Other is on todo author's free account.
    "TD003",
    "TD005",
    "TD007",

    # We understood when to use pseudo-random generators.
    "S311",

    # we often don't want to care about number of function arguments,
    # especially if they are inside pytest's fixture
    "PLR0913",

    # Doesn't recognize new "match" syntax
    "E999",

    # Do not restrict calling functions in defaults (fastapi requirement).
    "D",

    # Do not restrict calling functions in defaults (fastapi requirement).
    "B008",

    # Why is it bad to pass string literal directly to exception raised?
    "EM101",
    "EM102",

    # Passing PascalCase names is allowed.
    "N",

    # Sometimes it's typehinting-wise to declare variable and assign it
    # in different logical branches before returning.
    "RET504",

    # Not clear why first branch of if-elif-else should not contain raise
    # statement.
    "RET505",
    "RET506",

    # It's ok to have "continue" and then "else: raise...".
    "RET507",

    # Escaping inner quotes to not change outer ones is OK.
    "Q003",

    # No strict rules for string concatenation.
    "ISC002",
    "ISC003",

    # Builtin shadowing is allowed in local contexts.
    "A",

    # To not search for specific error code on type ignoring.
    "PGH003",

    # Do not replace symbols in false-positive scenario.
    "RUF001",

    # Ternary operator often breaks line-length limit and decreases
    # readability.
    "SIM108",

    # Allow commented-out code.
    "ERA001",

    # Too often gives false-positive.
    "S105",

    "ANN",
    "PT",
    "ARG",
    "FBT",
]

[per-file-ignores]
"test_*.py" = ["S101", "PLR2004"]
"testing.py" = ["S101", "PLR2004"]
"conftest.py" = ["S101", "F811", "PLR2004"]

[mccabe]
max-complexity = 10
